#!/usr/bin/env bash
# prints subdomains of argument (domain)

subdomains="www lb-01 web-01 web-02"

if [ "$#" -lt 1 ];
then
    echo "must provide with a domain"
    exit
fi

dom="$1"
if [ "$#" -ge 2 ];
then
    subdomains="$2"
fi

for sub in $subdomains; do
    dig "$sub.$dom" | grep -A1 'ANSWER SECTION:' | tail -n1 > temp.txt
    echo -n "The subdomain $sub"
    awk '{print " is a " $4 " record and points to "$5}' temp.txt
done
rm temp.txt
