#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo sed -i '46 i \\tif (\\$request_filename ~ redirect_me) {\n\t\t rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
