#!/usr/bin/env bash
# redirecting

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/server_name _;/a server_name _;\n\tlocation \/redirect_me {\n\t\t return 301  https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
