#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo sed -i '52 i \\tlocation /redirect_me {\n\t\treturn 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
sed -i '/location/a \\t\terror_page 404 /code_404.html;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/code_404.html
sudo service nginx restart
