#!/usr/bin/env bash
# configure haproxy for lb

apt update
apt install -y haproxy=1.6.\*

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3282-web-01 104.196.177.213:80 check
    server 3282-web-02 34.74.177.102:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
