#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

n=1
while [ $n -le 100 ]
do
	str=""
	if [ $(( n % 3 )) -eq 0 ]
	then
		str+="Fizz"
	fi
	if [ $(( n % 5 )) -eq 0 ]
	then
		str+="Buzz"
	fi
	if [ -z "$str" ]
	then
		echo "$n"
	else
		echo "$str"
	fi
	(( n++ ))
done
