#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
if grep "face" ~/hosts.new; then
	:
else
	echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
